### ISSUE TITLE
Build error on Windows 10

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/opossum#109]
**Node.js Version:**
8.9.0
**Operating System:**
Windows 10
**Steps to Produce Error:**
`npm it`

```
$ npm it
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-TWILfEnvO7I8mFe35d98F6T5fbLaEtbFTG/lxWvid8qDfFTxt19EBijWmB4j3+Hoh5TfHE2faWs73ua+EphuBA== integrity checksum failed when using sha512: wanted sha512-TWILfEnvO7I8mFe35d98F6T5fbLaEtbFTG/lxWvid8qDfFTxt19EBijWmB4j3+Hoh5TfHE2faWs73ua+EphuBA== but got sha1-9qn+xBzFCh3lD6M2A6tYCZH2Bo4=. (23892 bytes)
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.

> electron@1.6.11 postinstall C:\Users\hf\Desktop\dev\opossum\node_modules\electron
> node install.js

npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> opossum@1.3.0 prepublish C:\Users\hf\Desktop\dev\opossum
> nsp check && npm run build:browser

(+) No known vulnerabilities found

> opossum@1.3.0 build:browser C:\Users\hf\Desktop\dev\opossum
> browserify index.js lib/*.js > dist/opossum.js

Error: Cannot find module 'C:\Users\hf\Desktop\dev\opossum\lib\*.js' from 'C:\Users\hf\Desktop\dev\opossum'
    at C:\Users\hf\Desktop\dev\opossum\node_modules\resolve\lib\async.js:55:21
    at load (C:\Users\hf\Desktop\dev\opossum\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\hf\Desktop\dev\opossum\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\hf\Desktop\dev\opossum\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opossum@1.3.0 build:browser: `browserify index.js lib/*.js > dist/opossum.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opossum@1.3.0 build:browser script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hf\AppData\Roaming\npm-cache\_logs\2017-11-10T10_54_48_577Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opossum@1.3.0 prepublish: `nsp check && npm run build:browser`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opossum@1.3.0 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hf\AppData\Roaming\npm-cache\_logs\2017-11-10T10_54_49_041Z-debug.log
```

Related to https://github.com/bucharest-gold/entente/issues/179

**Comment by lance** [comment]
Is this the case for all versions of node? Seems odd.

**Comment by helio-frota** [comment]
@lance I think this was my fault.
opossum uses `make`, so this is not prepared to run the build with `npm it`.
I'm installing `make` for windows to check again.

**Comment by helio-frota** [comment]
no, it still failing with make:

```console
hf@DESKTOP-137Q3FQ MINGW64 ~/Desktop/dev/opossum (master)
$ make
npm run lint

> opossum@1.3.0 lint C:\Users\hf\Desktop\dev\opossum
> eslint test/*.js index.js lib/*.js

npm run build:browser

> opossum@1.3.0 build:browser C:\Users\hf\Desktop\dev\opossum
> browserify index.js lib/*.js > dist/opossum.js

Error: Cannot find module 'C:\Users\hf\Desktop\dev\opossum\lib\*.js' from 'C:\Users\hf\Desktop\dev\opossum'
    at C:\Users\hf\Desktop\dev\opossum\node_modules\resolve\lib\async.js:55:21
    at load (C:\Users\hf\Desktop\dev\opossum\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\hf\Desktop\dev\opossum\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\hf\Desktop\dev\opossum\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opossum@1.3.0 build:browser: `browserify index.js lib/*.js > dist/opossum.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opossum@1.3.0 build:browser script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hf\AppData\Roaming\npm-cache\_logs\2017-11-23T14_12_29_165Z-debug.log
Makefile:2: recipe for target 'ci' failed
make: *** [ci] Error 1

hf@DESKTOP-137Q3FQ MINGW64 ~/Desktop/dev/opossum (master)
$ make ci
npm run lint

> opossum@1.3.0 lint C:\Users\hf\Desktop\dev\opossum
> eslint test/*.js index.js lib/*.js

npm run build:browser

> opossum@1.3.0 build:browser C:\Users\hf\Desktop\dev\opossum
> browserify index.js lib/*.js > dist/opossum.js

Error: Cannot find module 'C:\Users\hf\Desktop\dev\opossum\lib\*.js' from 'C:\Us                                                                                                                                                                                               ers\hf\Desktop\dev\opossum'
    at C:\Users\hf\Desktop\dev\opossum\node_modules\resolve\lib\async.js:55:21
    at load (C:\Users\hf\Desktop\dev\opossum\node_modules\resolve\lib\async.js:6                                                                                                                                                                                               9:43)
    at onex (C:\Users\hf\Desktop\dev\opossum\node_modules\resolve\lib\async.js:9                                                                                                                                                                                               2:31)
    at C:\Users\hf\Desktop\dev\opossum\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opossum@1.3.0 build:browser: `browserify index.js lib/*.js > dist/oposs                                                                                                                                                                                               um.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opossum@1.3.0 build:browser script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                                                                                                               ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hf\AppData\Roaming\npm-cache\_logs\2017-11-23T14_13_09_649                                                                                                                                                                                               Z-debug.log
Makefile:2: recipe for target 'ci' failed
make: *** [ci] Error 1
```

**Comment by helio-frota** [comment]
seems to be a problem with browserify or browserify-usage :
because it works when using `browserify index.js lib/circuit.js` instead `browserify index.js lib/*.js`

and eslint works fine using wildcards

```console
hf@DESKTOP-137Q3FQ MINGW64 ~/Desktop/dev/opossum (master)
$ npm install
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> opossum@1.3.0 prepublish C:\Users\hf\Desktop\dev\opossum
> nsp check && npm run build:browser

(+) No known vulnerabilities found

> opossum@1.3.0 build:browser C:\Users\hf\Desktop\dev\opossum
> browserify index.js lib/circuit.js > dist/opossum.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 115 packages in 17.579s
```

**Comment by helio-frota** [comment]
seems to be the same issue:
https://github.com/browserify/browserify/issues/1170

**Comment by helio-frota** [comment]
also to avoid:

```console
hf@DESKTOP-137Q3FQ MINGW64 ~/Desktop/dev/opossum (pr)
$ npm install
npm ERR! path C:\Users\hf\Desktop\dev\opossum\node_modules\fsevents\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'C:\Users\hf\Desktop\dev\opossum\node_modules\fsevents\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'C:\Users\hf\Desktop\dev\opossum\node_modules\fsevents\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\Users\\hf\\Desktop\\dev\\opossum\\node_modules\\fsevents\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'C:\\Users\\hf\\Desktop\\dev\\opossum\\node_modules\\fsevents\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hf\AppData\Roaming\npm-cache\_logs\2017-11-23T15_02_19_626Z-debug.log
```

we need to run like this: `npm install --force`

**Comment by helio-frota** [comment]
closing
